name: MasterBan
version: 1.0
main: me.peter.test.Test
author: Peter and Jeffin
description: A Banning Plugin!
 
commands:
     MasterBan:
         usage: /<command>
         description: Bans a player!
